#Script to parse output csv files for 12 hour data
#those scripts are generated by the script edgeR_from_FC.R (same directory)

rm(list=ls())

library(gplots)
library(dplyr)

get_up_lax = function(in_file){
  ret_list = filter(filter(in_file, FDR < 0.05), logFC > 1)
  return(ret_list)
}

get_down_lax = function(in_file){
  ret_list = filter(filter(in_file, FDR < 0.05), logFC < -1)
  return(ret_list)
}

get_up_strict = function(in_file){
  ret_list = filter(filter(in_file, FDR < 0.05), logFC > 2)
  return(ret_list)
}

get_down_strict = function(in_file){
  ret_list = filter(filter(in_file, FDR < 0.05), logFC < -2)
  return(ret_list)
}

files <- list.files(path="/Users/MacProMatt/Desktop/edgeR_out", pattern="*.csv", full.names=TRUE, recursive=FALSE)

ISGList <- read.csv("/Users/MacProMatt/Desktop/Langlois_Lab/ISG_list_R.csv")
ISGList$mgi_symbol = toupper(ISGList$mgi_symbol)

#We get 300/310 genes when filtering by ensembl ID and 290/310 when filtering by mgi_id, so we will filter by ensembl id
#The missing 10 could be excluded because of missing symbols or they were filtered out due to having too low of baseline expression across samples

for (i in files){
  filter_file = read.csv(i)
  ISG_out = filter(filter_file, Input %in% ISGList$genes)
  my_file = write.csv(ISG_out, file = paste(dirname(i), 'ISGs', basename(i), sep = '/'))
}

ISG_low_naive = read.csv('/Users/MacProMatt/Desktop/edgeR_out/ISGs/low_versus_naive.csv')
ISG_high_naive = read.csv('/Users/MacProMatt/Desktop/edgeR_out/ISGs/high_versus_naive.csv')

high_up_lax_naive = get_up_lax(ISG_high_naive)
low_up_lax_naive = get_up_lax(ISG_low_naive)

write.csv(low_up_lax_naive, file = '/Users/MacProMatt/Desktop/LOW_UP_LAX.csv')
write.csv(high_up_lax_naive, file = '/Users/MacProMatt/Desktop/HIGH_UP_LAX.csv')

only_high = filter(high_up_lax_naive, !Symbol %in% low_up_lax_naive $Symbol)
only_low = filter(low_up_lax_naive, !Symbol %in% high_up_lax_naive $Symbol)
intersect = filter(high_up_lax_naive, !Symbol %in% high_up_lax_naive $Symbol)
